### ISSUE TITLE
Error when running setup file

### ISSUE THREAD

**Issue by un-lock-me** [JohnTailor/tkm#1]
Hi,
I tried to run ur code, it raises an error which I could not resolve it 
there is little work around that in the net

/home/saria/anaconda3/envs/condaenv27/bin/python2.7 /home/saria/Downloads/tkm-master/setup.py
Warning: Extension name '_topicAssign' does not match fully qualified name 'tkm-master._topicAssign' of '_topicAssign.pyx'
Compiling _topicAssign.pyx because it changed.
[1/1] Cythonizing _topicAssign.pyx

Error compiling Cython file:
------------------------------------------------------------
...
#cython: language_level=3
^
------------------------------------------------------------

_topicAssign.pyx:1:0: 'tkm-master._topicAssign' is not a valid module name
Traceback (most recent call last):
  File "/home/saria/Downloads/tkm-master/setup.py", line 22, in <module>
    ext_modules = cythonize(extensions),
  File "/home/saria/anaconda3/envs/condaenv27/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1027, in cythonize
    cythonize_one(*args)
  File "/home/saria/anaconda3/envs/condaenv27/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1149, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: _topicAssign.pyx

Process finished with exit code 1

would you please have a look on that

**Comment by JohnTailor** [comment]
Rename the folder tkm-master to TKM.
The dash "-" in "tkm-master" is not a valid character for a module.

**Comment by un-lock-me** [comment]
Thank u So much,

You are righ, it is my mistake :|
Now when I run test.py I got this error:

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    import TKMCore
  File "/home/saria/Downloads/tkm/TKMCore.py", line 10, in <module>
    import algTools
  File "/home/saria/Downloads/tkm/algTools.py", line 9, in <module>
    from stemming.porter import stem
ImportError: No module named stemming.porter

I believe the problem is with "from stemming.porter import stem" as I can not install it on anaconda environment

Do U have any idea regarding this? Also I couldnt find exactly this one in the documentation of NLTK ,

Thanks

**Comment by JohnTailor** [comment]
Install from https://pypi.python.org/pypi/stemming/1.0
